# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: pkm-data/files/yolo/  # dataset root dir
train: ./val  # train images (relative to 'path') 4 images
val: ./test  # val images (relative to 'path') 4 images

# Classes dictionary
names:
  0: poke_card